# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-10-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locaciones', '0001_initial'),
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_procedencia', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('nro_procedencia', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('lat_procedencia', models.FloatField(default=0)),
                ('long_procedencia', models.FloatField(default=0)),
                ('calle_estudio', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('nro_estudio', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('lat_estudio', models.FloatField(default=0)),
                ('long_estudio', models.FloatField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Alumnos')),
                ('localidad_estudio', models.ForeignKey(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, on_delete=django.db.models.deletion.CASCADE, related_name='domicilios_estudio', to='Locaciones.Localidades')),
                ('localidad_procedencia', models.ForeignKey(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, on_delete=django.db.models.deletion.CASCADE, to='Locaciones.Localidades')),
            ],
        ),
    ]
