# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-09-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Depositos', '0001_initial'),
        ('Transportes', '0001_initial'),
        ('Clientes', '0001_initial'),
        ('Vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actividad', models.DateField()),
                ('total_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Clientes.Clientes')),
                ('codigo_deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Depositos.Depositos')),
                ('codigo_transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transportes.Transportes')),
                ('codigo_vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vendedores.Vendedores')),
            ],
            options={
                'db_table': 'datos_generales',
            },
        ),
    ]
