# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-10-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_familiares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('cant_hijos', models.IntegerField(default=0)),
                ('nombre_padre', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('apellido_padre', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('vive_padre', models.BooleanField(default=True)),
                ('nivel_estudio_padre', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('nombre_madre', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('apellido_madre', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('vive_madre', models.BooleanField(default=True)),
                ('nivel_estudio_madre', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Alumnos')),
            ],
        ),
    ]
