# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-09-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=50)),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('webpage', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=35, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo', models.CharField(max_length=8)),
                ('razonSocial', models.CharField(blank=True, max_length=50, null=True)),
                ('debaja', models.BooleanField(default=False)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locaciones.Localidades')),
            ],
        ),
    ]
