# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-09-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('debaja', models.BooleanField(default=False)),
                ('suspendido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'transportes',
            },
        ),
    ]
