# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-10-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='localidades',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locaciones.Provincias'),
        ),
    ]
