# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-10-02 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidades',
            name='debaja',
        ),
    ]
