# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-10-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('apellido', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('genero', models.CharField(blank=True, max_length=256, null=True)),
                ('pais_documento', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('tipo_documento', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('nro_documento', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('nacionalidad', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('cuil', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('pueblos_originarios', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('obra_social', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('telefono', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('email', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('codigo', models.CharField(max_length=256)),
                ('esRegular', models.BooleanField(default=False, error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'})),
                ('carrera', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
