# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2025-10-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_ocupacionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio_secundario', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('anio_egreso_secundario', models.IntegerField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'})),
                ('condicion_laboral', models.CharField(error_messages={'blank': 'Este campo es requerido.', 'null': 'Este campo es requerido.'}, max_length=256)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Alumnos')),
            ],
        ),
    ]
